name = "uintdev-blog"
compatibility_date = "2025-08-07"

routes = [
    { pattern = "blog.uint.dev", custom_domain = true }
]

workers_dev = false
preview_urls = false

[build]
command = "chmod +x ./build.sh && ./build.sh"

[assets]
directory = "./public/"
not_found_handling = "404-page"
