name = "uintdev-blog"
compatibility_date = "2025-06-04"

routes = [
    { pattern = "testblog.uint.dev", custom_domain = true }
]

workers_dev = false
preview_urls = false

[assets]
directory = "./public/"
not_found_handling = "404-page"
